[feature] Review, Tag 엔터티 추가
boocam-project/FastTime-backend pull request #153
Opened 2023-12-18 14:07 UTC by ghrltjdtprbs

### [feature] Review, Tag 엔터티 추가
- 하나의 리뷰에 여러 개의 태그가 있고, 각 태그도 여러 개의 리뷰에 사용될 수 있기 때문에 ManyToMany 로 설정
- 태그 중복을 허용하지 않기 때문에 Set으로 받아옴
- rating 유효성 검사

2023-12-19 01:27 UTC, JeongUijeong requested changes
수고하셨습니다! 😊 몇 가지 코멘트 남겼으니 참고하셔서 수정 부탁드립니다!
더불어 줄이 2줄 띄어져 있는 부분도 한 줄 공백으로 수정해주시면 감사하겠습니다! 🤍

2023-12-19 01:27 UTC, JeongUijeong commented on src/main/java/com/fasttime/domain/review/entity/Review.java
> +public class Review extends BaseTimeEntity {
@Getter 가 필요할 것 같아요 ㅎㅎ

2023-12-19 01:27 UTC, JeongUijeong commented on src/main/java/com/fasttime/domain/review/entity/Tag.java
> +public class Tag {
@Getter 가 필요할 것 같고, @NoArgsConstructor에 접근레벨 설정 해주시면 좋을 것 같습니다. 😄

2023-12-19 01:33 UTC, Nine-JH requested changes
`@ManyToMany` 보다는 중간테이블을 하나 만드는게 더 좋아보이네요!

2023-12-19 03:04 UTC, ghrltjdtprbs commented on src/main/java/com/fasttime/domain/review/entity/Review.java
> +public class Review extends BaseTimeEntity {
피드백 감사합니다. 후에 @Builder를 사용할 수도 있어 일부러 제외했습니다! 구현 과정에서 추가하도록 하겠습니다 ㅎㅎ😊

2023-12-19 03:04 UTC, ghrltjdtprbs commented on src/main/java/com/fasttime/domain/review/entity/Tag.java
> +public class Tag {
수정하여 커밋했습니다! 확인해주세요 ㅎㅎ

2023-12-19 06:08 UTC, ghrltjdtprbs commented
> `@ManyToMany` 보다는 중간테이블을 하나 만드는게 더 좋아보이네요!

중간테이블 ReviewTag 생성해 커밋 했습니다! 확인해주세요

2023-12-20 12:23 UTC, Nine-JH approved these changes

2023-12-20 15:42 UTC, merged