[Feature] 리뷰 등록, 삭제 구현
boocam-project/FastTime-backend pull request #177
Opened 2024-01-18 08:59 UTC by ghrltjdtprbs

## [Feature] 리뷰 등록, 삭제 구현

### 리뷰 등록 구현
 - 리뷰 작성 구현.
 - 부트캠프 이름, 제목, 내용, 긍정태그, 부정태그, 별점 작성 가능.
 - 엔드포인트 : POST api/v2/reviews
 
### 리뷰 삭제 구현
 - 리뷰 삭제 구현.
 - soft delete 적용
 - 엔드포인트 : DELETE api/v2/reviews/{reviewId}

----------------
### 특이 사항
- 부트캠프 인증로직 구현안함(인증 로직 구현 후 예외처리 추가 예정)
- 테스트 완료 
![image](https://github.com/fcstudy-project/FastTime-backend/assets/105612931/b9ef6dc4-ea04-4ac6-a524-842d0b071af2)

2024-02-05 07:20 UTC, chimaek reviewed
리뷰 완료 고생 많이했어요~

2024-02-05 07:20 UTC, chimaek commented on src/main/java/com/fasttime/domain/member/entity/Member.java
@Setter가 있어용.

2024-02-05 07:20 UTC, chimaek commented on src/main/java/com/fasttime/domain/member/entity/Member.java
> +    private boolean campCrtfc = false;
@Builder.Default로 초기화하는 방식도 고려해보세용

2024-02-05 07:20 UTC, chimaek commented on src/main/java/com/fasttime/domain/review/controller/ReviewController.java
각 메서드 부분의 매핑 부분에서 URL이 중복되는데영

@RequestMapping으로 중복을 최소화 해보죠!

2024-02-05 07:20 UTC, chimaek commented on src/main/java/com/fasttime/domain/review/controller/ReviewController.java
> +        return ResponseEntity.ok(ResponseDTO.res(HttpStatus.CREATED,"리뷰작성이 완료되었습니다.", responseDTO));
`return ResponseEntity.status(HttpStatus.CREATED).body(ResponseDTO.res(HttpStatus.CREATED, "리뷰작성이 완료되었습니다.", responseDTO));`

이게 RESTful에 적절합니다.

2024-02-05 07:20 UTC, chimaek commented on src/main/java/com/fasttime/domain/review/controller/ReviewController.java
```"리뷰작성이 완료되었습니다.", "리뷰삭제가 완료되었습니다.", "리뷰수정이 완료되었습니다."```

이렇게 하드코딩하는 것보다는 상수로 정의해보는 건 어떨까요?

2024-02-05 07:20 UTC, chimaek commented on src/main/java/com/fasttime/domain/review/exception/ReviewAlreadyDeletedException.java
JavaDoc 주석을 넣어보죠 앞으로는 유지,보수성을 위해 넣는것이 좋겠습니다.

2024-02-05 07:20 UTC, chimaek commented on src/main/java/com/fasttime/domain/review/service/ReviewService.java
> +        review.setupdate(requestDTO.title(),requestDTO.rating(),requestDTO.content());
setupdate 네이밍 확인요

2024-02-05 07:20 UTC, chimaek commented on src/main/java/com/fasttime/domain/review/dto/response/ReviewResponseDTO.java
> +            .map(tagId -> tagRepository.findById(tagId)
tagRepository를 dto내부에 있어선 될까요? 외부 레이어 단에서 데이터를 만들고(getTagContents와 같은 함수를 서비스 레이어에 위치한다던지?) dto에 전달하는것이 효율있어보입니다.

2024-02-05 07:20 UTC, chimaek commented on src/main/java/com/fasttime/domain/review/service/ReviewService.java
> +        return this.tagRepository;
확인바래요 ㅎㅎ 굳이 이 메서드가 필요할까요?

2024-02-05 10:57 UTC, JeongUijeong requested changes
수고하셨습니다!👍🏻 
저희 TDD 방식으로 개발하기로 했었는데, 테스트 코드가 보이지 않네요..!
구현이 먼저 되긴 했지만, 어쨋든 테스트 코드도 추가로 작성해주시면 좋을 것 같습니다~
또, 몇 가지 코멘트 적어두었으니 확인 부탁 드립니다~~😊

2024-02-05 10:57 UTC, JeongUijeong commented on src/main/java/com/fasttime/domain/review/entity/ReviewTag.java
> +@AllArgsConstructor
빌더 패턴을 쓰기로 했던 것 같은데 혹시 필드가 3개 뿐이라서 의도적으로 AllArgeConstructor 애노테이션을 사용하신 걸까요? 😊

2024-02-05 10:57 UTC, JeongUijeong commented on src/main/java/com/fasttime/domain/review/service/ReviewService.java
> +            .orElseThrow(() -> new MemberNotFoundException());
알고 계시겠지만 혹시 도움이 될까 적어봅니다. 이렇게 표현하는 것도 방법도 있으니, 참고만 해주세요~😊
```suggestion
            .orElseThrow(MemberNotFoundException::new);
```

2024-02-06 09:58 UTC, ghrltjdtprbs commented on src/main/java/com/fasttime/domain/review/entity/ReviewTag.java
> +@AllArgsConstructor
해당 테이블은 중간 테이블이라 빌더 패턴을 적용하지 않는 것이 더 효율적이라고 판단했습니다! 요청하신다면 추가하겠습니다 ㅎㅎ 👍👍

2024-02-06 14:13 UTC, ghrltjdtprbs commented on src/main/java/com/fasttime/domain/member/entity/Member.java
수정했습니다! 58367f91c438eddc665ffcc1047d2e5002ac7eb6 커밋 확인해주세요ㅎㅎ

2024-02-06 14:14 UTC, ghrltjdtprbs commented on src/main/java/com/fasttime/domain/member/entity/Member.java
> +    private boolean campCrtfc = false;
b74c205195589ed06192b4bfa7e032b7f1480407 확인해주세요! 이렇게 하는게 맞나 모르겠네요.. 😭😭

2024-02-06 14:14 UTC, ghrltjdtprbs commented on src/main/java/com/fasttime/domain/review/controller/ReviewController.java
07e00c40587ff7133ef3a40c6bf06b4eeba83504 확인해주세요!

2024-02-06 14:15 UTC, ghrltjdtprbs commented on src/main/java/com/fasttime/domain/review/controller/ReviewController.java
> +        return ResponseEntity.ok(ResponseDTO.res(HttpStatus.CREATED,"리뷰작성이 완료되었습니다.", responseDTO));
반영했습니다! 2d6c4cc27e8f73f3f1c6edb2c8f8ac9f4d421269 확인해주세요 ㅎㅎ

2024-02-06 14:17 UTC, ghrltjdtprbs commented on src/main/java/com/fasttime/domain/review/controller/ReviewController.java
우선 성공 메시지를 "리뷰 요청이 완료되었습니다." 로 통일해 상수로 정의했습니다! aef2042d315687dd2edc5d24ffca66fb032969f7 확인해주세요! 만약 필요하다면 enum 클래스로 따로 관리 하는 것이 좋겠네요! 좋은 의견 감사합니다!!  👍👍

2024-02-06 14:19 UTC, ghrltjdtprbs commented on src/main/java/com/fasttime/domain/review/service/ReviewService.java
> +        review.setupdate(requestDTO.title(),requestDTO.rating(),requestDTO.content());
자바 네이밍 컨벤션에 따라 변경하였습니다! (setupdate -> updateReviewDetails) 868b0b1f66e302de5227fb984c34f7bc34636850 확인해주세요! 😊😊

2024-02-06 14:20 UTC, ghrltjdtprbs commented on src/main/java/com/fasttime/domain/review/dto/response/ReviewResponseDTO.java
> +            .map(tagId -> tagRepository.findById(tagId)
맞습니다! dto 전체적으로 수정했습니다. acc5f1c78d0ae7b1df43c053c3a4b5185a079e68 확인해주세요👍👍

2024-02-06 14:20 UTC, ghrltjdtprbs commented on src/main/java/com/fasttime/domain/review/service/ReviewService.java
> +        return this.tagRepository;
이 부분은 제가 놓쳤습니다.. 메서드 삭제했으니 확인해주세요! acc5f1c78d0ae7b1df43c053c3a4b5185a079e68

2024-02-06 14:21 UTC, ghrltjdtprbs commented on src/main/java/com/fasttime/domain/review/service/ReviewService.java
> +            .orElseThrow(() -> new MemberNotFoundException());
확인했습니다! 알려주셔서 감사합니다 ㅎㅎ 😊😊

2024-02-06 14:23 UTC, ghrltjdtprbs commented
> 리뷰 완료 고생 많이했어요~

피드백 전부 반영해 커밋했습니다! 확인해주세요 ㅎㅎ

2024-02-06 14:24 UTC, ghrltjdtprbs commented
> 수고하셨습니다!👍🏻 저희 TDD 방식으로 개발하기로 했었는데, 테스트 코드가 보이지 않네요..! 구현이 먼저 되긴 했지만, 어쨋든 테스트 코드도 추가로 작성해주시면 좋을 것 같습니다~ 또, 몇 가지 코멘트 적어두었으니 확인 부탁 드립니다~~😊

테스트 코드는 다음 pr에 작성해 올리겠습니다! 감사합니다 ㅎㅎ 😊😊😊

2024-02-08 07:39 UTC, KwonJuHwan approved these changes

2024-02-08 07:40 UTC, JeongUijeong approved these changes
수고하셨습니다~!😊👍🏻❤️

2024-02-08 07:41 UTC, merged