[fix] 리뷰 등록, 수정시 태그 등록문제 해결
boocam-project/FastTime-backend pull request #179
Opened 2024-02-19 10:04 UTC by ghrltjdtprbs

문제 사항 :
 - 리뷰를 등록, 수정시 review_tag 테이블에 데이터 저장이 안됨.
 - goodtag, badtag 구분을 안하고 저장함 -> 조회시 태그 구분 불가 변경 사항 :
 - Review 엔터티에 tag cascade 추가
 - goodtag, badtag 구분을 위해 ReviewTag에 boolean타입의 isGoodTag 추가
 - 리뷰 수정, 재등록시 기존 리뷰 태그 삭제 후 재등록하는 것으로 로직 수정

2024-02-21 09:53 UTC, Kongji82 approved these changes

2024-02-21 09:53 UTC, Kongji82 commented on src/main/java/com/fasttime/domain/review/entity/ReviewTag.java
> +    private boolean isGoodTag;
good tag, bad tag 구분은 Review가 아니라 Tag 엔티티에서 하는거 어떻게 생각하시나요?

2024-02-21 09:53 UTC, Kongji82 commented on src/main/java/com/fasttime/domain/review/service/ReviewService.java
> +                updateReviewTags(existingReview, requestDTO);
중복 부분이 있어서 따로 함수화해도 될것 같습니다.

2024-02-21 09:53 UTC, Kongji82 commented on src/main/java/com/fasttime/domain/review/service/ReviewService.java
> +        updateReviewTags(review, requestDTO);
(중복)

2024-02-21 10:46 UTC, JeongUijeong requested changes
수고하셨습니다~😊
몇 가지 코멘트 달아뒀으니 확인 후 답변 부탁드립니다! ㅎㅎ
특히 리뷰 조회 시 페이지네이션 기능 부재에 대해 재고해주시면 좋을 것 같아요 😊

2024-02-21 10:46 UTC, JeongUijeong commented on src/main/java/com/fasttime/domain/review/controller/ReviewController.java
> +    @GetMapping("/all")
RESTful API의 조회는 collection 목록을 받는 행위입니다! 따라서 `/all`을 PATH에 붙일 필요가 없습니다~
PATH에 붙이는 조건은 필터라고 생각하시고 설계하시면 좋다고 합니다! 😊

2024-02-21 10:46 UTC, JeongUijeong commented on src/main/java/com/fasttime/domain/review/controller/ReviewController.java
> +        @RequestParam(required = false, defaultValue = "createdAt") String sortBy) {
getReviews와 다른 점이 쿼리 파라미터로 bootcamp 문자열을 받는 것 뿐인 것 같습니다~ 
getReviews에서 쿼리 파라미터로 bootcamp 문자열을 받게 한 후 required = false로 설정하시는 방법은 어떤가요?
그 후 Service나 Repository에서 처리하시면 좋을 것 같습니다. 
1. 쿼리 파라미터로 bootcamp에 문자열을 담아 요청했는지 확인 후 각각 해당하는 메서드 호출
2. 요청 정보에 따라 Repository에서 BooleanBuilder를 통해 다른 조건문 생성

2024-02-21 10:46 UTC, JeongUijeong commented on src/main/java/com/fasttime/domain/review/controller/ReviewController.java
> +    @GetMapping("/all")
추가적으로 부트캠프 후기 목록 조회에서 페이지네이션 기능이 필요 없을까요?

2024-02-21 10:46 UTC, JeongUijeong commented on src/main/java/com/fasttime/domain/review/controller/ReviewController.java
> +        @RequestParam(required = false, defaultValue = "createdAt") String sortBy) {
페이지네이션 기능이 추가된다면 더불어 QueryDSL로 구현하시면 좋을 것 같습니다~

2024-02-21 10:46 UTC, JeongUijeong commented on src/main/java/com/fasttime/domain/review/controller/ReviewController.java
> +    @GetMapping("/by-bootcamp/summary")
모든 부트캠프에 대한 리뷰 요약 정보를 한 번에 조회하는 기능인 건가요? 특정 부트캠프에 대한 리뷰 요약 정보를 조회하는 API가 이 기존에 들었던 기획에 좀 더 적합한 것 같습니다!

부트캠프 목록 조회 -> 부트캠프 선택 -> 선택한 부트캠프 리뷰 요약 정보 조회 + 선택한 부트캠프 리뷰 목록 조회(페이지네이션?)

저는 이렇게 이해했었는데 혹시 제가 잘못 이해하고 있는 부분이 있다면 알려주시면 감사하겠습니다..!🥲

2024-02-21 10:46 UTC, JeongUijeong commented on src/main/java/com/fasttime/domain/review/entity/ReviewTag.java
> +    private boolean isGoodTag;
ReviewTag 엔터티는 Review와 Tag의 다대다 관계 연결을 위한 단순한 중간 테이블인 걸로 이해했습니다! 또한, 실제로 긍정적인지 아닌 지를 판단할 대상도 Tag 이기 때문에 Tag 테이블에 추가하는 것이 좋아 보입니다!

2024-02-21 10:48 UTC, ghrltjdtprbs commented on src/main/java/com/fasttime/domain/review/controller/ReviewController.java
> +    @GetMapping("/all")
/all을 붙인 이유는 securityconfig에 등록하기 위해 임의로 붙였습니다! 페이지네이션은 저도 생각은 했으나, 프론트와 상의 후에 붙이려고 일단 보류해뒀습니다!

2024-02-21 10:51 UTC, ghrltjdtprbs commented on src/main/java/com/fasttime/domain/review/controller/ReviewController.java
> +    @GetMapping("/by-bootcamp/summary")
figma에 추가한 와이어프레임을 참고해주세요! 이 부분도 상의 후에 리팩토링 하는 것이 좋을 것 같습니다 👍👍
 
<img width="306" alt="image" src="https://github.com/boocam-project/FastTime-backend/assets/105612931/df12fe54-1827-4c8f-b8eb-eaad7f41bab1">

2024-02-21 10:53 UTC, ghrltjdtprbs commented on src/main/java/com/fasttime/domain/review/entity/ReviewTag.java
> +    private boolean isGoodTag;
구현 중에 임의로 추가한 부분이라 중간테이블에 isGoodTag필드를 넣었습니다! 말씀대로 Tag 엔터티에서 처리하는게 좋을 것 같네요 ㅎㅎ 수정하겠습니다! 😊😊

2024-02-21 10:54 UTC, ghrltjdtprbs commented on src/main/java/com/fasttime/domain/review/entity/ReviewTag.java
> +    private boolean isGoodTag;
구현 중에 임의로 넣은 필드라 판단을 잘못한 것 같습니다! isGoodTag은 말씀대로 Tag 테이블에 추가하는게 좋을 것 같네요! 수정하겠습니다 ㅎㅎ 👍👍

2024-02-21 11:07 UTC, JeongUijeong commented on src/main/java/com/fasttime/domain/review/controller/ReviewController.java
> +    @GetMapping("/by-bootcamp/summary")
네! 감사합니다~ 이미지를 보니, 부트캠프 이름, 별점, 리뷰 개수는 목록 조회 시에 주는 게 이해가 됩니다!
하지만, 태그 총 개수, 태그별 개수는 따로 부트캠프 선택했을 때 주는 것이 좋을 것 같네요! API를 분리해야 할 것 같습니다🥲

2024-02-21 11:11 UTC, JeongUijeong commented on src/main/java/com/fasttime/domain/review/controller/ReviewController.java
> +    @GetMapping("/all")
넵 답변 감사합니다! 😊
```
.requestMatchers(HttpMethod.GET, "api/v2/reviews").permitAll()
```
securityconfig에서는 위처럼 GET 매핑에 대해서만 허용해두시면 됩니다~

2024-02-22 07:55 UTC, ghrltjdtprbs commented on src/main/java/com/fasttime/domain/review/service/ReviewService.java
> +                updateReviewTags(existingReview, requestDTO);
피드백 반영해 수정하였습니다! 44c10b8209d695ae2ddf631f3813ff769be958e3 커밋 확인해주세요 👍👍

2024-02-22 07:56 UTC, ghrltjdtprbs commented on src/main/java/com/fasttime/domain/review/controller/ReviewController.java
> +    @GetMapping("/all")
피드백 반영해 엔드포인트 수정했습니다! eaa7e659c2555b5b3bbec6c2650705021384784a 커밋 확인해주세요 😊😊

2024-02-22 07:57 UTC, ghrltjdtprbs commented on src/main/java/com/fasttime/domain/review/controller/ReviewController.java
> +        @RequestParam(required = false, defaultValue = "createdAt") String sortBy) {
피드백 반영해 기존 부트캠프별 리뷰 조회 api를 삭제하고 조회에 통합했습니다! b28c0b4763136f895b5d7f2ef5e82f5247bc9393 커밋 확인해주세요!! ㅎㅎ 👍

2024-02-22 07:59 UTC, ghrltjdtprbs commented on src/main/java/com/fasttime/domain/review/controller/ReviewController.java
> +    @GetMapping("/by-bootcamp/summary")
리뷰 조회시 페이지네이션 적용할 것을 고려해, 부트캠프 요약 정보/ 태그 그래프 정보를 출력하는 api 를 분리하였습니다!  832d876ebcc2a785547da0311da16c2fcd58f2d4 커밋 확인해주세요! 👍👍

2024-02-22 08:00 UTC, ghrltjdtprbs commented
> 수고하셨습니다~😊 몇 가지 코멘트 달아뒀으니 확인 후 답변 부탁드립니다! ㅎㅎ 특히 리뷰 조회 시 페이지네이션 기능 부재에 대해 재고해주시면 좋을 것 같아요 😊

피드백 전부 반영해 커밋하였으니 참고해주세요! 페이지네이션은 천천히....😭

2024-02-22 13:28 UTC, JeongUijeong approved these changes
수고했어용~🩷

2024-02-22 13:28 UTC, merged

2024-02-22 13:48 UTC, KwonJuHwan commented on src/main/java/com/fasttime/domain/review/controller/ReviewController.java
> +    @GetMapping("/summary")
해당 API 조회마다 DB에서 많은 데이터를 조회하므로, 캐싱처리가  필요해보입니다.
간편하게 Redis Caching 기능을 구현할 수 있으므로 추천드립니다.
Redis Caching :
- RedisCacheConfig를 통해, CacheManager Bean 등록
- 캐싱 처리가 필요한 서비스 로직에 @Cacheable 어노테이션 추가
- 캐싱 삭제가 필요한 서비스 로직( ex. 등록)에 @CacheEvict 어노테이션 추가
- 예시가 궁금하시면 해당 링크를 통해, 확인해주세요.
- @Cacheable 예시 - https://github.com/CoolPeace-yanolza/backend/blob/develop/src/main/java/com/coolpeace/domain/dashboard/service/DashboardService.java
- @CacheEvict 예시 - https://github.com/CoolPeace-yanolza/backend/blob/develop/src/main/java/com/coolpeace/domain/statistics/service/DailyStatisticsService.java
- RedisCacheConfig 예시 - https://github.com/CoolPeace-yanolza/backend/blob/develop/src/main/java/com/coolpeace/global/config/RedisCacheConfig.java