[feat] 스터디 모집글 댓글 CRUD 기능을 추가한다.
boocam-project/FastTime-backend pull request #262
Opened 2024-04-28 05:30 UTC by KwonJuHwan

# Pull Request 요약

- 스터디 모집글에 대한 댓글 CRUD를 개발하였습니다.

## 변경 사항

스터디 댓글 엔티티 추가
스터디 댓글 Repository 추가
스터디 댓글 Service 추가
스터티 댓글 Controller 추가
스터티 댓글 CRUD 기능 구현
스터디 댓글 엔티티, Service 테스트 추가
스터디 API docs test 추가
스터디 모집글 리스트 조회 API의 권한을 변경하였습니다. (인증 -> permit All)

## 관련 이슈

- close #259 
- close #260
- close #261

## 개발 유형

- [ ] 새로운 기능 개발
- [ ] 테스트 코드 작성
- [ ] 문서 업데이트
- 기타 (아래에 설명 추가)

## 작업 기간

- 작업 시작일: (2024-04-21)
- 작업 종료일: (2024-04-28)

## 유의사항

- 원래는 의정님이 구현해주신 Comment 엔티티를 이용하여 구현하려고 했지만 다음과 같은 우려사항이 있었습니다.
1.  Article의 의존성이 강하다
2. 로직 변경 시, Article과 관련된 Side effect가 우려된다.
3. 댓글의 유지보수가 어렵다.

따라서, 의정님이 구현해주신 Comment를 베이스로 하여 StudyComment 엔티티로 해당 기능을 구현하였습니다. 

## 참고문헌
- 의정님의 Comment 엔티티에 대한 CRUD

2024-04-28 05:30 UTC, chimaek commented on src/docs/asciidoc/study_comment/studyComment-api.adoc
> +include::{snippets}/StudyComment-delete/http-response.adoc[]
주요 의견 및 개선 사항:

1. 코드가 문서화 목적으로 사용되고 있으므로, 주석(Comment)이 `REST API Docs`를 설명하는데 도움이 됩니다.
2. `==`, `===`와 같은 구분선을 추가해 텍스트 구조를 더욱 명확하게 만들 수 있습니다.
3. 많은 문서들이 `include`되고 있는데, 각각의 파일들이 최신 상태인지 확인할 필요가 있습니다.
4. API 엔드포인트에 대한 보안 관련 내용(인증, 권한 등)이 부족하며, 추가될 필요가 있습니다.
5. 요청과 응답 필드가 충분히 명세화되었는지 확인이 필요합니다.
6. 요청 필드의 유효성 검사에 대한 내용도 추가할 수 있습니다.
7. 전체 문서의 일관성을 유지하기 위해 언어 및 스타일을 통일할 필요가 있습니다.

이러한 제안을 고려하여 코드 리뷰를 보다 완성도있게 만들 수 있습니다.

2024-04-28 05:30 UTC, chimaek commented on src/main/java/com/fasttime/domain/studyComment/controller/StudyCommentController.java
> +}
주요 변경 사항:
1. 코드는 외부 종속성이 높은 것으로 보입니다. 생성자 주입 및 롬복의 `@RequiredArgsConstructor`를 통해 의존성을 주입하고 있습니다.
2. 상태코드를 직접 지정하는 대신 HTTP 상태 코드별 정적 메소드를 사용할 수 있습니다.

향상 제안:
1. `GetStudyCommentsRequestDTO.builder().studyId(studyId).memberId(memberId).parentStudyCommentId(parentStudyCommentId).build()`이 너무 길어서 가독성이 좋지 않습니다. 타입일치 및 널 체크를 고려하는 등의 개선이 필요합니다.
2. `StudyCommentPageRequestDTO.builder().page(page).size(pageSize).build().of()`에서 마지막 `.of()` 호출은 불필요합니다. Builder로부터 반환된 값만 반환하면 됩니다.
3. 보안 상 고려사항: 현재 사용자 아이디를 강조합니다. 보안 검토 결과 권한 확인 및 사용자 인증 프로세스가 코드에 따라 적용되어야 합니다.

오류 위험:
1. `StudyCommentController`에서 `CreateStudyCommentRequestDTO` 및 `UpdateStudyCommentRequestDTO`에 대한 입력 유효성 검사는 수행 중이지만, 출력 결과에 대한 사용자 인증 및 권한 검사 과정이 누락되었습니다. 사용자 권한을 확인하는 로직을 추가해야 합니다.

그외:
코드 리뷰는 더 많은 세부 정보를 포함할 수 있지만 위 내용은 주요 변경 사항과 개선 제안을 요약한 것입니다.

2024-04-28 05:30 UTC, chimaek commented on src/main/java/com/fasttime/domain/studyComment/dto/request/CreateStudyCommentRequestDTO.java
> +}
코드 리뷰:

1. @Getter를 사용하여 content 필드에 대한 getter 메서드가 생성되었으므로, setter 메서드는 없습니다. 만약 이 필드를 수정할 수 있는 기능이 필요하다면 setter 메서드를 추가해야 합니다.

2. parentStudyCommentId 필드에 대한 유효성 검사가 없습니다. 이 필드도 필요에 따라 유효성을 검사하는 어노테이션을 추가하는 것이 좋습니다.

3. jakarta.validation.constraints 패키지가 import 되어 있는데, 당신의 프로젝트에서 이 패키지를 사용하고 있지 않다면 javax.validation.constraints 패키지로 변경하는 것이 좋을 수 있습니다.

4. 주석은 여러 줄로 표현될 수 있으며 코드의 의도를 더 명확하게 설명할 수 있습니다. 주석을 추가하여 해당 DTO의 목적 및 사용 방법을 설명하는 것이 좋습니다.

5. 클래스 및 메서드에 자바독 주석을 추가하여 코드의 가독성을 향상시킬 수 있습니다.

6. 필요에 따라 equals(), hashCode() 및 toString() 메소드를 재정의하여 객체의 비교 및 출력을 쉽게 할 수 있습니다.

2024-04-28 05:31 UTC, chimaek commented on src/main/java/com/fasttime/domain/studyComment/dto/request/GetStudyCommentsRequestDTO.java
> +}
이 코드 패치에 대한 간단한 코드 리뷰입니다:

1. 생성자가 `private`로 선언되어 있어 외부에서 인스턴스화할 수 없습니다. `@Builder` 애노테이션을 사용했지만, 생성자는 `public`으로 선언해야 합니다.

2. 불변 객체로 선언하기 위해 필드를 `final`로 표시했지만, `@Getter`만 있고 `setter`가 없어 필드 값이 변경되지 않습니다. 이것이 의도된 동작인지 확인이 필요합니다.

3. `GetStudyCommentsRequestDTO` 클래스의 목적과 역할이 명확하게 주석으로 설명되어 있는 것이 좋습니다.

4. `studyId`, `memberId`, `parentStudyCommentId`에 대한 입력 유효성 검사 로직이 없으므로 나중에 추가하는 것이 좋습니다.

5. 변수명은 충분히 명확하지만, 주석이 추가로 포함된다면 가독성이 향상될 수 있습니다.

6. 코드 스타일은 일관성 있고 깔끔합니다. 다만, Java 관례에 맞게 클래스 이름을 대문자로 시작하는 것이 바람직합니다.

7. 더 나아가, 기타 주석이나 문서화 작업을 통해 클래스의 용도와 기능을 더 잘 설명할 수 있습니다.

2024-04-28 05:31 UTC, chimaek commented on src/main/java/com/fasttime/domain/studyComment/dto/request/StudyCommentPageRequestDTO.java
> +}
이 코드는 비교적 깔끔하게 작성되어 있습니다. 그러나 다음과 같은 개선 사항을 고려할 수 있습니다:

1. **상수 위치 변경**: `DEFAULT_SIZE`와 `MAX_SIZE` 변수는 매번 객체 생성 시마다 재계산됩니다. 효율을 높이기 위해 클래스 수준으로 상수를 선언하는 것이 좋습니다.
   
2. **스프링 버전**: `org.springframework.data.domain.PageRequest`가 deprecated 되었습니다. 최신 버전에 맞춰 사용하는 것이 좋습니다.

3. **의존성 주입**: 생성자에서 받은 `int page`와 `int size`를 그대로 사용하고 있지만, 유효성 검사 또는 데이터 처리를 따로 수행할 필요가 있다면 추가할 수 있습니다.

4. **주석**: 간단한 주석을 추가하여 메서드 및 변수의 역할을 명확히할 수 있습니다.

5. **불변성**: `page`와 `size`가 변경되지 않아야 하므로 변수를 `final`로 선언하여 불변성을 보장합니다.

6. **예외 처리**: 페이지 값이 음수인 경우에 대한 예외 처리가 필요할 수 있습니다.

7. **테스트**: 해당 클래스에 대한 단위 테스트를 작성하여 동작을 검증하는 것이 중요합니다.

개선된 코드는 다음과 같이 될 수 있습니다:

```java
package com.fasttime.domain.studyComment.dto.request;

import org.springframework.data.domain.PageRequest;
import lombok.Builder;

public final class StudyCommentPageRequestDTO {

    private final int page;
    private final int size;
    private static final int DEFAULT_SIZE = 10;
    private static final int MAX_SIZE = 50;

    @Builder
    public StudyCommentPageRequestDTO(int page, int size) {
        this.page = Math.max(page, 0);
        this.size = size > MAX_SIZE ? DEFAULT_SIZE : size;
    }

    public PageRequest of() {
        return PageRequest.of(page, size);
    }
}
```

이러한 개선으로 코드를 더 견고하게 만들고 확장성을 갖출 수 있습니다.

2024-04-28 05:31 UTC, chimaek commented on src/main/java/com/fasttime/domain/studyComment/dto/request/UpdateStudyCommentRequestDTO.java
> +}
코드 리뷰:

1. `UpdateStudyCommentRequestDTO` 클래스가 올바르게 구성되어 있는 것 같습니다.
2. 어노테이션을 통해 빈 값이 들어올 수 없도록 `@NotBlank`를 사용하고, 내용의 길이를 제한하기 위해 `@Size`를 사용한 것이 좋은 점입니다.
3. 그러나 실제로 유효성 검사를 수행하는 메서드인 `@Valid` 어노테이션이 없는데, 이는 해당 DTO 객체가 사용될 때 유효성 검사가 일어나지 않을 수 있다는 의미입니다. 따라서 컨트롤러에서 DTO 객체를 받을 때 `@Valid` 어노테이션을 함께 사용하여 유효성을 검사하는 것이 좋습니다.
4. `content` 필드의 데이터 타입이 `String`으로 지정되어 있지만, 보다 명확한 유니코드 문자열 처리를 위해 `char[]` 나 `StringBuilder`와 같은 타입으로 변경할 수 있습니다.
5. 추가적으로 Java의 `assert` 키워드를 활용하여 내부 불변성을 체크하는 등의 방어적 프로그래밍을 더 할 수 있습니다.

이 코드는 기본적으로 유효성 검사에 관한 부분에서 잘 처리되었으며, 주요 개선 사항은 `@Valid` 어노테이션의 추가 및 데이터 타입 변경 정도로 요약됩니다.

2024-04-28 05:31 UTC, chimaek commented on src/main/java/com/fasttime/domain/studyComment/dto/response/StudyCommentListResponseDTO.java
> +}
이 코드 조각은 비교적 간단한 DTO 클래스를 정의하고 있습니다. 여기에 몇 가지 개선 제안과 버그 위험 사항을 고려해보겠습니다:

1. `StudyCommentListResponseDTO`는 주로 데이터 전송 객체로 사용되므로, 직렬화(Serialization)와 역직렬화(Deserialization)를 고려하여 Serializable 인터페이스를 구현하는 것이 좋습니다.
2. 변수 `totalComments`의 자료형을 long으로 선언했는데, 음수 값일 필요가 없다면 양수만 받는 자료형(예: unsigned int)을 사용하는 것도 고려할 가치가 있습니다.
3. 불변성(Immutability)을 보장하기 위해 클래스 내의 속성들을 final로 선언할 수 있습니다.
4. `totalPages`와 `isLastPage`의 변수명에서 약간의 혼란이 있을 수 있으므로 더 명확한 이름으로 변경할 수 있습니다.
5. Builder 패턴을 사용하는 이유가 명확하지 않으면 Builder를 제거하고 기본 생성자와 Setter 메서드를 추가하는 방법도 고려해 볼 수 있습니다.

위의 제안은 코드의 가독성, 확장성 및 유지보수성을 향상시키는 데 도움이 될 수 있습니다.

2024-04-28 05:31 UTC, chimaek commented on src/main/java/com/fasttime/domain/studyComment/dto/response/StudyCommentResponseDTO.java
> +}
이 코드 패치는 Lombok을 사용하여 DTO 클래스를 정의하고 있습니다. 다음은 몇 가지 개선 제안 및 버그 리스크입니다:

1. `StudyCommentResponseDTO`에 대한 테스트 코드 작성이 권장됩니다.
2. `createdAt`, `updatedAt`, `deletedAt` 필드의 유효성 검사 또는 포맷팅이 추가로 필요할 수 있습니다.
3. `@EqualsAndHashCode` 애노테이션 사용 여부 고려.

주의할 점:
- 롬복을 사용하므로 롬복 구성과 관련된 설정이 제대로 적용되었는지 확인해야 합니다.
- `@Builder`를 사용할 때 모든 필드에서 생성자를 생성하도록 강제할지 여부를 고려해야 합니다.

이상입니다.

2024-04-28 05:31 UTC, chimaek commented on src/main/java/com/fasttime/domain/studyComment/entity/StudyComment.java
> +}
이 코드의 주요 사항은 다음과 같습니다:

1. `StudyComment` 엔티티는 `BaseTimeEntity`를 상속하고 있으며, 생성자 및 업데이트 메서드를 포함하고 있습니다.
2. `StudyComment`는 `Study`와 `Member`와 관계가 있습니다. 그러나 `MappedBy` 사용 여부를 고려해야 합니다.
3. `delete()` 메서드에서 자식 댓글들도 삭제되어야 하므로 재귀적인 호출을 수행하고 있습니다.
4. `toCommentResponseDTO()` 메서드에서는 DTO로 변환하는 로직을 구현하고 있습니다. 자식 댓글의 삭제 여부 등을 고려하여 DTO를 만들고 있습니다.
5. `dateTimeParse()` 메서드는 `LocalDateTime`을 문자열로 변환하는 데 사용됩니다.

개선 제안:
1. 엔티티 간의 관계 (`ManyToOne`, `OneToMany`) 설정이 올바르게 이루어졌는지 확인합니다.
2. `fetch` 전략을 설정하여 데이터베이스를 효율적으로 조회할 수 있도록 개선할 수 있습니다.
3. `nullable=false` 속성을 사용하여 필수 요소에 대한 유효성을 설정합니다.
4. DTO 변환 로직을 별도의 클래스로 분리하여 엔티티와 DTO 간 변환을 명확히 할 수 있습니다.
5. 코드 가독성을 높이기 위해 메서드나 변수명을 명확하게 작성합니다.

전체적으로 코드의 구조 및 일관성이 괜찮아 보입니다. 후속 리팩터링 및 테스트 시 주의사항을 살펴보면 도움이 됩니다.

2024-04-28 05:31 UTC, chimaek commented on src/main/java/com/fasttime/domain/studyComment/exception/NotStudyCommentAuthorException.java
> +}
이 코드는 주석이 없지만 보여지는대로 NotStudyCommentAuthorException 클래스를 정의하는 것으로 보입니다. 

1. **장점**:
   - 적합한 예외 계층 구조 (`ApplicationException`을 확장) 및 오류 코드 (`ERROR_CODE`)
   - 코드는 간결하며 목적을 분명히 한다.

2. **개선 사항**:
   - 주석: 왜 이 예외가 필요한지, 어떤 상황에서 발생하는지에 대해 주석을 추가하면 도움이 될 수 있습니다.
   - 문서화: `ERROR_CODE` 설명과 사용 방법에 대한 설명이 필요합니다.
   - 테스트: 테스트 케이스 또는 사용 예제가 필요합니다.
   - 로깅: 에러와 관련된 정보를 로그에 기록하여 추적성을 높일 수 있습니다.

3. **버그 위험**:
   - 상속: `ApplicationException`이 적절한 예외 클래스인지 확인해야 합니다.
   - `ERROR_CODE` 사용: `ERROR_CODE`에 대해 충분한 테스트가 필요합니다.

4. **추가 제안**:
   - 코드 컨벤션 준수: 현재 프로젝트의 컨벤션과 일관성 있게 작성되었는지 확인하세요.
   - `toString()` 메서드 구현: 예외 인스턴스를 문자열로 표시하는 경우 유용 할 수 있습니다.

코드 리뷰 후 결정적인 판단은 전체 시스템 구조 및 요구사항에 따라 다를 수 있습니다.

2024-04-28 05:31 UTC, chimaek commented on src/main/java/com/fasttime/domain/studyComment/exception/StudyCommentNotFoundException.java
> +}
코드 리뷰:

1. `StudyCommentNotFoundException` 클래스에는 기본 생성자만 있어서 다른 생성자 유형이 필요할 수도 있습니다.
2. `ERROR_CODE` 변수를 `final`로 선언하여 값이 변경되지 않도록 하는 것이 좋습니다.
3. 예외 메시지를 추가하여 누락된 스터디 댓글의 정보나 이유를 포함시키면 사용자가 문제를 이해하는 데 도움이 됩니다.
4. 적절한 JavaDoc 주석을 추가하여 클래스와 메서드의 목적 및 사용법을 설명하면 좋습니다.
5. 필요한 경우 테스트 코드를 작성하여 예외가 올바르게 처리되는지 확인하는 것이 중요합니다.

위 제안 사항들은 코드의 유지보수성과 가독성을 향상시킬 수 있습니다.

2024-04-28 05:31 UTC, chimaek commented on src/main/java/com/fasttime/domain/studyComment/repository/StudyCommentCustomRepository.java
> +}
이 코드 패치는 새로운 `StudyCommentCustomRepository` 인터페이스를 도입하는 것 같습니다. 코드의 구조 자체는 깨끗하고 단순해 보입니다. 그러나 몇 가지 사소한 향상점과 버그 위험을 고려해야 합니다.

1. 메서드 시그니처 및 네이밍:
   - `findAllBySearchCondition` 메서드명이 약간 길 수 있습니다. 더 명확한 이름으로 변경하는 것이 좋을 수 있습니다.
   - 파라미터명에서 `DTO`가 지칭되는 객체의 역할에 대해 명확히 작성하는 것이 도움이 됩니다.

2. Null 처리:
   - `getStudyCommentsRequestDTO` 및 `pageable`이 null일 가능성에 대비하여 null 체크를 추가하는 것이 안전할 수 있습니다.

3. 문서화:
   - JavaDoc 주석을 추가하여 각 메서드가 하는 일을 설명하는 것이 좋습니다.
   
4. 예외 처리:
   - 예외가 발생할 수 있는 경우에 대한 적절한 예외 처리 로직을 추가해야 할 수 있습니다.

5. 요청된 데이터 양식 검증:
   - `GetStudyCommentsRequestDTO`에서 요청된 데이터의 유효성을 검증하는 로직이 필요할 수 있습니다.

6. 성능 개선:
   - 쿼리의 성능 최적화를 위해 필요한 경우에는 해당 부분을 리뷰하고 개선할 필요가 있습니다.

2024-04-28 05:32 UTC, chimaek commented on src/main/java/com/fasttime/domain/studyComment/repository/StudyCommentCustomRepositoryImpl.java
> +}
이 코드는 QueryDSL을 사용하여 데이터베이스에서 StudyComment 엔티티를 조회하는 Spring Data JPA 리포지터리 구현체입니다. 

잠재적인 버그 위험은 다음과 같습니다:
1. ``createSearchConditionsBuilder`` 메소드에서 각 조건을 AND 연산으로 처리하고 있지만, OR 연산이 필요한 경우를 고려하지 않고 있습니다.
2. ``StudyCommentCustomRepositoryImpl`` 클래스 내부에 있는 ``createSearchConditionsBuilder`` 메소드가 재사용될 수 있는 부분이 많기 때문에 이를 더 유연하게 만들 수 있습니다.

개선 제안은 다음과 같습니다:
1. 적절한 주석을 추가하여 각 메소드의 역할과 동작 방식을 명확히 설명합니다.
2. 쿼리 파라미터로 받는 값에 대한 유효성 검사를 추가하여 예외 상황 처리를 보강합니다.
3. 코드 스타일을 일관되게 유지하기 위해 들여쓰기 및 스타일 가이드라인을 확인합니다.
4. 성능 향상을 위해 쿼리 결과를 캐시하거나 인덱스를 추가할 수 있는 가능성을 고려합니다.

이러한 수정 사항과 추가적인 테스트를 통해 코드의 안정성과 성능을 향상시킬 수 있습니다.

2024-04-28 05:32 UTC, chimaek commented on src/main/java/com/fasttime/domain/studyComment/repository/StudyCommentRepository.java
> \ No newline at end of file
주어진 코드 조각은 스프링 데이터 JPA를 사용하여 StudyComment 엔티티에 대한 레포지토리를 정의하는 것입니다. 개발자가 특정 로직을 처리하기 위해 `StudyCommentCustomRepository`를 구현하여 확장하고 있습니다. 

버그나 중요한 위험 요소는 나타나지 않으며, 좋은 점은 다음과 같습니다:
- JPA 레포지토리 인터페이스(`JpaRepository`)를 올바르게 상속하고 있습니다.
- 추가적인 메서드가 필요한 경우 이를 `StudyCommentCustomRepository`에서 구현할 수 있습니다.

개선 제안은 아래와 같습니다:
- 파일의 끝에 새 줄을 추가하거나 `No newline at end of file` 경고를 해결할 수 있습니다. (가독성을 위해 규칙화된 끝 부분을 유지하는 것이 좋습니다)

2024-04-28 05:32 UTC, chimaek commented on src/main/java/com/fasttime/domain/studyComment/service/StudyCommentService.java
> +}
이 코드는 주석 및 문서화가 부족하며 몇 가지 개선 사항이 있습니다. 여기에는 삽입된 코드 전체의 문제점만 집중합니다:

1. `getComments` 메서드에서, `commentsFromDB.forEach(comment -> comments.add(comment.toCommentResponseDTO()));` 부분은 대량의 댓글을 가져올 때 성능에 영향을 줄 수 있습니다. 대신, 페이지네이션 방식으로 데이터를 로드하여 처리할 것을 권장합니다.

2. `checkDuplicateCondition` 메서드가 조건 검사를 하나씩 증가시키며 중복 조건을 확인하는 방식은 확장성이 낮고 유지보수가 어려울 수 있습니다. 대신, `stream()`과 `filter()`를 사용하여 보다 간결하고 확장 가능한 방법을 고려해 볼 수 있습니다.

3. 코드 내에서 `LocalDateTime`를 사용하는 부분이 다수 있으며, 시간대(time zone) 관리가 필요할 수 있습니다. 시간 관련 작업에 대해 명확한 방향을 설정하여 일관된 결과를 얻을 수 있도록 합니다.

4. 일부 메서드가 매우 길거나 한 가지 이상의 역할을 하는 것으로 보입니다. 이러한 메서드를 더 작고 단일 책임을 가진 메서드로 분할하는 것을 고려해야 합니다.

5. 예외 처리가 충분한지 확인하고, 적절한 에러 메시지를 포함하도록 수정할 필요가 있습니다. 특히 예외 발생 시 원인에 대한 정보를 포함하는 것이 유용합니다.

6. 코드 일관성을 유지하기 위해 코드 스타일을 확인하고 Lombok 애노테이션을 일관되게 사용하는 것이 좋습니다. 선언 순서에 대해서도 정리하여 일관성을 유지하는 것이 좋습니다.

2024-04-28 05:32 UTC, chimaek commented on src/main/java/com/fasttime/global/config/SpringSecurityConfig.java
>                  .anyRequest().authenticated())
이 코드 패치의 주요 사항은 다음과 같습니다:

- `permitAll()`은 해당 URL에 대한 모든 요청을 허용한다.
- 요청 메소드와 URL 패턴에 따라 액세스 권한을 설정하고 있다.
- 수정된 부분에서는 `api/v2/resumes/**` 및 `api/v2/studies` 엔드포인트가 GET 메소드로 호출될 때 모두 허용되도록 조정되었다.

개선 제안:
- 충분한 테스트가 수행되었는지 확인하십시오. 보안 문제가 발생하지 않도록 적절히 검증되어야 합니다.
- 코드 주석을 추가해 가독성을 높일 수 있습니다.
- 보안 취약점을 최소화하기 위해 필요한 인증/권한 확인을 확실히 하십시오.
- 예외 처리가 적절히 이루어지도록 하여 프로그램의 안정성을 보장하세요.

2024-04-28 05:32 UTC, chimaek commented on src/main/java/com/fasttime/global/exception/ErrorCode.java
>      UNSUPPORTED_DATA_TYPE_FOR_NOTIFICATION_SENDING(HttpStatus.INTERNAL_SERVER_ERROR,
주석에 나와 있는 내용대로 댓글 관련 에러 코드를 추가했습니다. 새로 추가된 코드 부분에서 발견된 버그나 위험성은 없어 보입니다. 그러나 개선을 제안드리자면, 각각의 enum 항목에 대해 상세한 설명이 주석으로 달려 있으면 이해가 빠를 것입니다. 더불어, Enum 상수 순서를 일관적으로 유지하면 향후 코드의 가독성을 높일 수 있습니다. 따라서 해당 Enum 클래스 전체를 살펴보고 일관성 있는 순서로 Enum 상수를 정렬하는 것이 좋습니다.

2024-04-28 05:32 UTC, chimaek commented on src/main/resources/db/migration/V28__Add_studyComment_table.sql
> +    ADD CONSTRAINT FK_STUDY_COMMENT_ON_PARENT_STUDY_COMMENT FOREIGN KEY (study_comment_parent_id) REFERENCES study_comment (id);
위의 코드 조각을 간단히 검토해 보았습니다.
1. 테이블 생성 부분에서 NULL을 허용하는 'created_at' 및 'updated_at' 필드는 기본값(default value)을 지정하는 것이 권장됩니다.
2. 'content' 필드의 크기(255)를 고려해 사용 용도에 맞는 적절한 크기로 지정하는 것이 좋습니다.
3. 외래 키 제약 조건(constraint)을 추가할 때 해당 열의 값들이 연결되는 대상 테이블에 존재하는지 여부를 확인하고, 없다면 어떻게 처리할지 고려해야 합니다.
4. 특히, study_comment_parent_id가 해당 테이블의 ID를 참조하고 있는데, 이것이 자기 자신을 참조할 수 있어 재귀적인 구조를 형성할 수 있으므로, 관련 처리를 신중히 해주어야 합니다.
5. 마지막으로 SQL 스크립트 실행순서 및 테이블 간 의존성을 고려하여 외래 키 추가 순서를 결정하는 것이 중요합니다.

개선 및 버그 리스크에 대해 검토해 주시기 바랍니다.

2024-04-28 05:32 UTC, chimaek commented on src/test/java/com/fasttime/domain/studyComment/docs/StudyCommentControllerDocsTest.java
> +}
Hello! How can I assist you today?

2024-04-28 05:32 UTC, chimaek commented on src/test/java/com/fasttime/domain/studyComment/unit/entity/StudyCommentTest.java
> +}
이 코드는 꽤 좋습니다. 그러나 일부 개선을 제안할 수 있습니다:
1. `study` 및 `member`가 null로 설정될 수 있는데도 `StudyComment.builder().study(null).member(null)`에서 대신 더 전문적인 경우의 테스트 델타를 사용하여이 구성요소를 초기화하는 것이 더 바람직합니다.
2. 유닛 테스트 명은 TextEditingController보다 유의미하게 변경되어야 합니다. 각 테스트는 예상 결과에 대한 설명을 담고 있어야하며 함수 이름에 그대로 복사해야합니다.
3. Test 클래스에 대한 javadoc을 추가하십시오.
4. Mockito/PowerMockito와 같은 Mocking 라이브러리를 사용하여 Study Comment 인스턴스의 삭제시 현재 시간을 가로채는 방법을 조사하십시오.

기본적으로 코드는 읽기 쉽고 목적이 분명하며 테스트 커버리지를 높일만한 좋은 부분들이 많습니다. 외부 종속성 테스트 (예를 들어, LocalDateTime.now() 호출)을 고려하여 이 문제를 해결하려면 Mockito 또는 PowerMockito와 같은 라이브러리를 고려하십시오.

2024-04-28 05:32 UTC, chimaek commented on src/test/java/com/fasttime/domain/studyComment/unit/service/StudyCommentServiceTest.java
> +}
Hello! How can I assist you today?

2024-05-03 01:22 UTC, ghrltjdtprbs approved these changes
수고하셨습니다! 몇 가지 의견 남겨놨으니 참고해주세요 ㅎㅎ 😊😊

2024-05-03 01:22 UTC, ghrltjdtprbs commented on src/main/java/com/fasttime/domain/studyComment/dto/request/UpdateStudyCommentRequestDTO.java
DTO에 record를 사용하는 방법도 고려해보시면 좋을 것 같습니다! @Getter,@NoArgsConstructor,@AllArgsConstructor와 같은 메서드들을 자동으로 생성해주기 때문에 코드도 간결해지고, 기본적으로 불변 객체를 생성하므로 데이터의 불변성도 보장됩니다 👍👍

2024-05-03 01:22 UTC, ghrltjdtprbs commented on src/main/java/com/fasttime/domain/studyComment/service/StudyCommentService.java
getComment와 getComments와 같은 읽기 작업만 수행하는 메서드에 @Transactional(readOnly=true)를 적용하면 좋을 것 같습니다! 😊

2024-05-03 04:05 UTC, chimaek approved these changes
👍

2024-05-03 11:10 UTC, JeongUijeong approved these changes
수고하셨습니당~👍🏻

2024-05-03 12:12 UTC, Kongji82 reviewed
고생하셨습니다👍👍

2024-05-03 12:12 UTC, Kongji82 commented on src/main/java/com/fasttime/domain/studyComment/entity/StudyComment.java
> +
DTO로 변환하는 메소드를 엔티티 내부가 아니라 다른 곳에서 하는게 어떨까요?
개인적인 생각으로는 엔티티는 DB와 상호 작용에 대한 책임을 가지는데 DTO로 변환은 이와 관계가 없기에 단일책임원칙에 위배된다고 생각합니다. 그리고 후에 엔티티 클래스가 DTO에 의존관계를 가지기 때문에 유지보수에도 불리해 보입니다

2024-05-05 08:37 UTC, ghrltjdtprbs requested changes

2024-05-05 08:37 UTC, ghrltjdtprbs commented on src/main/resources/db/migration/V28__Add_studyComment_table.sql
스크립트 번호가 중복됩니다! 현재 V29번 스크립트까지 존재하니 V30으로 파일명을 변경해주세요! 😊

2024-05-10 13:30 UTC, chimaek commented on src/main/java/com/fasttime/global/util/WebDriverUtil.java
>          if (ObjectUtils.isEmpty(System.getProperty("webdriver.chrome.driver"))) {
코드 리뷰:
- 파일 이름이나 클래스명이 "WebDriverUtil" 인 것으로 보아 이 클래스가 WebDriver를 관리하는 유틸리티로 사용되는 것으로 추정됨.
- WEB_DRIVER_PATH가 변경되었으며, 리눅스 경로인데 확장자(.exe)가 Windows에 해당하는 것이 남아있어 수정 필요.
- getChromeDriver() 메서드 내의 로직은 환경변수 "webdriver.chrome.driver"가 비어있을 때 Chromedriver를 로드하는데 처리가 잘 되어 있음.
- 주석은 영어로 작성되어 있지만 코드는 한국어로 주로 작성되어 있음.

개선 제안:
- 상수 이름을 대문자와 언더스코어(_) 형태로 쓰는 것이 일반적이므로 WEB_DRIVER_PATH를 WEB_DRIVER_PATH 로 수정하는 것을 고려해 볼 수 있음.
- 파일 경로에 대한 확장자 ".exe" 를 삭제하여 리눅스 시스템에서도 문제없이 작동하도록 할 수 있음.

2024-05-10 13:52 UTC, KwonJuHwan commented on src/main/resources/db/migration/V28__Add_studyComment_table.sql
변경하였습니다~

2024-05-10 13:54 UTC, ghrltjdtprbs approved these changes
수고하셨습니다~👍

2024-05-10 13:56 UTC, merged